# local_backend: true

backend:
  name: github
  repo: Alkademi-Development/lailatulcoding-intern-web

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "faq"
    label: "faq"
    folder: "faq"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Question", name: "question", widget: "string"}
      - {label: "Answer", name: "answer", widget: "markdown"}
  
   
